config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :mma_gyms


  get 'pages/mma_gyms'
  get 'pages/about'
  get 'pages/contact'

  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/city.rb
class City < ActiveRecord::Base 
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/mma_gym.rb
class MmaGym < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  
   def slug_candidates
      [:name, :city]  
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :county, :state_id)
    end
end

app/controllers/mma_gyms_controller.rb
class MmaGymsController < ApplicationController
  before_action :set_mma_gym, only: [:show, :edit, :update, :destroy]

  # GET /mma_gyms
  # GET /mma_gyms.json
  def index
    @mma_gyms = MmaGym.all
  end

  # GET /mma_gyms/1
  # GET /mma_gyms/1.json
  def show
  end

  # GET /mma_gyms/new
  def new
    @mma_gym = MmaGym.new
  end

  # GET /mma_gyms/1/edit
  def edit
  end

  # POST /mma_gyms
  # POST /mma_gyms.json
  def create
    @mma_gym = MmaGym.new(mma_gym_params)

    respond_to do |format|
      if @mma_gym.save
        format.html { redirect_to @mma_gym, notice: 'Mma gym was successfully created.' }
        format.json { render :show, status: :created, location: @mma_gym }
      else
        format.html { render :new }
        format.json { render json: @mma_gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mma_gyms/1
  # PATCH/PUT /mma_gyms/1.json
  def update
    respond_to do |format|
      if @mma_gym.update(mma_gym_params)
        format.html { redirect_to @mma_gym, notice: 'Mma gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @mma_gym }
      else
        format.html { render :edit }
        format.json { render json: @mma_gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mma_gyms/1
  # DELETE /mma_gyms/1.json
  def destroy
    @mma_gym.destroy
    respond_to do |format|
      format.html { redirect_to mma_gyms_url, notice: 'Mma gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mma_gym
      @mma_gym = MmaGym.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mma_gym_params
      params.require(:mma_gym).permit(:name, :address, :city, :zip, :state, :phone, :website)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def mma_gyms
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/mma_gyms_helper.rb
module MmaGymsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cities/_form.html.haml
= form_for @city do |f|
  - if @city.errors.any?
    #error_explanation
      %h2= "#{pluralize(@city.errors.count, "error")} prohibited this city from being saved:"
      %ul
        - @city.errors.full_messages.each do |msg|
          %li= msg

  .row
  .form-group
  .col-md-6
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .row
  .form-group
  .col-md-6
    = f.label :county
    = f.text_field :county, class: 'form-control'
  .row
  .form-group
  .col-md-6
    = f.submit 'Save', class: 'btn btn-primary btn-lg'

app/views/cities/edit.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active Editing city
      .row
        .col-md-12
          %h2 Editing city

.container
  .row
    .col-md-12
    .row

%h1 Editing city

= render 'form'

= link_to 'Show', @city, class: 'btn btn-default'
\|
= link_to 'Back', cities_path, class: 'btn btn-default'

app/views/cities/index.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active Cities
      .row
        .col-md-12
          %h2 Cities

.container
  .row
    .col-md-12
    
%h1 Cities

%table.table.table-hover.table-striped
  %thead
    %tr
      %th Name
      %th County
      %th State
      %th
      %th
      %th

  %tbody
    - @cities.each do |city|
      %tr
        %td= city.name
        %td= city.county
        %td= city.state_id
        %td= link_to 'Show', city, class: 'btn btn-info'
        %td= link_to 'Edit', edit_city_path(city), class: 'btn btn-default'
        %td= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

%br

= link_to 'New City', new_city_path, class: 'btn btn-primary btn-lg'

app/views/cities/new.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active New City
      .row
        .col-md-12
          %h2 New City

.container
  .row
    .col-md-6
    .row

= render 'form'

.row
.form-group
.col-md-6
= link_to 'Back', cities_path, class: 'btn btn-default'

app/views/cities/show.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              = link_to "Home", root_path
            %li
              = link_to "Cities", cities_path
            %li.active 
              = @city.name
      .row
        .col-md-12
          %h2 
            = @city.name

.container
  .row
    .col-md-6
    .row

%p#notice= notice

%h1
  %b City:
  = @city.name
%h1
  %b County:
  = @city.county
%h1
  %b State:
  = @city.state_id

.row
.form-group
.col-md-6
= link_to 'Edit', edit_city_path(@city), class: 'btn btn-default'
\|
= link_to 'Back', cities_path, class: 'btn btn-default'

app/views/layouts/_footer.html.haml
%footer#footer
  .container
    .row
      .footer-ribon
        %span Keep in Touch Of Death
      .col-md-3
        .newsletter
          %h4 Newsletter
          %p Keep up on our always evolving product features and technology. Enter your e-mail and subscribe to our newsletter.
          #newsletterSuccess.alert.alert-success.hidden
            %strong Success!
            You've been added to our email list.
          #newsletterError.alert.alert-danger.hidden
          %form#newsletterForm{:action => "php/newsletter-subscribe.php", :method => "POST"}
            .input-group
              %input#email.form-control{:name => "email", :placeholder => "Email Address", :type => "text"}
                %span.input-group-btn
                  %button.btn.btn-default{:type => "submit"} Go!
      .col-md-3
        %h4 Feature Your Gym
        #tweet.twitter{"data-account-id" => ""}
          %p Interesting in adding your Gym? 
          %p Contact us for a quote.
      .col-md-4
        .contact-details
          %h4 Contact Us
          %ul.contact
            %li
              %p
                = fa_icon "map-marker fw"
                %strong Address:

            %li
              %p
                = fa_icon "phone fw"
                %strong Phone:
                (909) 556-3532
            %li
              %p
                = fa_icon "envelope fw"
                %strong Email:
                %a{:href => "mailto:info@mmagymsincalifornia.com"} info@mmagymsincalifornia.com
      .col-md-2
        %h4 Follow Us
        .social-icons
          %ul.social-icons
            %li.facebook
              %a{"data-placement" => "bottom", :href => "http://www.facebook.com/", :rel => "tooltip", :target => "_blank", :title => "Facebook"} Facebook
            %li.twitter
              %a{"data-placement" => "bottom", :href => "http://www.twitter.com/", :rel => "tooltip", :target => "_blank", :title => "Twitter"} Twitter
            %li.linkedin
              %a{"data-placement" => "bottom", :href => "http://www.linkedin.com/", :rel => "tooltip", :target => "_blank", :title => "Linkedin"} Linkedin
  .footer-copyright
    .container
      .row
        .col-md-12
        %div{:align => "center"}
          %p © Copyright 2015. All Rights Reserved.

app/views/layouts/_header.html.haml
%header
  .container
    %h1.logo
      %a{:href => "/"}
        = image_tag "logo.png", :alt => "MMA gyms In California", :data => {:"sticky-height" => 40, :"sticky-width" => 46}, :height => 108, :width => 122
    .search
      %form#searchForm{:action => "page-search-results.html", :method => "get"}
        .input-group
          %input#q.form-control.search{:name => "q", :placeholder => "Search...", :type => "text"}
            %span.input-group-btn
              %button.btn.btn-default{:type => "submit"}
                = fa_icon "search"
    %nav
      %ul.nav.nav-pills.nav-top
        %li
          %a{:href => "#"}
            = fa_icon "angle-right"
            Add A Gym
        %li.phone
          %span
            = fa_icon "phone"
            (909) 556-3532
    %button.btn.btn-responsive-nav.btn-inverse{"data-target" => ".nav-main-collapse", "data-toggle" => "collapse"}
      = fa_icon "bars"
  .navbar-collapse.nav-main-collapse.collapse
    .container

      .social-icons
        %ul.social-icons
          %li.facebook
            %a{:href => "#", :target => "_blank", :title => "Facebook"} Facebook
          %li.twitter
            %a{:href => "#", :target => "_blank", :title => "Twitter"} Twitter
          %li.linkedin
            %a{:href => "#", :target => "_blank", :title => "Linkedin"} Linkedin
      %nav.nav-main.mega-menu
        %ul#mainMenu.nav.nav-pills.nav-main
          %li.dropdown.active
            %a.dropdown-toggle{:href => "#"}
              Home
              = fa_icon "angle-down"

          %li.dropdown
            = link_to "#" do
              Dropdown
              = fa_icon "angle-down"
            %ul.dropdown-menu
              %li
                = link_to "Menu Item #1", "#"
              %li
                = link_to "Menu Item #2", "#"
              %li
                = link_to "Menu Item #3", "#"
          %li.dropdown
            %a.dropdown-toggle{:href => "/pages/about"}
              About
          %li.dropdown.mega-menu-item.mega-menu-fullwidth
            %a.dropdown-toggle{:href => "/mma_gyms"}
              MMA Gyms
              = fa_icon "angle-down"
            %ul.dropdown-menu
              %li
                .mega-menu-content
                  .row
                    .col-md-3
                      %ul.sub-menu
                        %li
                          %span.mega-menu-sub-title Northern California
                          %ul.sub-menu
                            %li
                              %a{:href => "#"} San Jose
                            %li
                              %a{:href => "#"} San Francisco
                            %li
                              %a{:href => "#"} Oakland
                            %li
                              %a{:href => "#"} Stockton
                            %li
                              %a{:href => "#"} Sacramento
                          %span.mega-menu-sub-title Central Valley
                          %ul.sub-menu
                            %li
                              %a{:href => "#"} Fresno
                            %li
                              %a{:href => "#"} Bakersfield                      
                    .col-md-3
                      %ul.sub-menu
                        %li
                          %span.mega-menu-sub-title Los Angeles
                          %ul.sub-menu
                            %li
                              %a{:href => "#"} Los Angeles
                            %li
                              %a{:href => "#"} Long Beach
                            %li
                              %a{:href => "#"} Glendale
                          %span.mega-menu-sub-title Orange County
                          %ul.sub-menu
                            %li
                              %a{:href => "#"} Anaheim
                            %li
                              %a{:href => "#"} Santa Ana
                            %li
                              %a{:href => "#"} Irvine         
                            %li
                              %a{:href => "#"} Huntington Beach                                                  
                    .col-md-3
                      %ul.sub-menu
                        %li
                          %span.mega-menu-sub-title Inland Empire
                          %ul.sub-menu
                            %li
                              %a{:href => "#"} Riverside
                            %li
                              %a{:href => "#"} San Bernardino
                            %li
                              %a{:href => "#"} Fontana
                            %li
                              %a{:href => "#"} Rancho Cucamonga
                    .col-md-3
                      %ul.sub-menu
                        %li
                          %span.mega-menu-sub-title San Diego
                          %ul.sub-menu
                            %li
                              %a{:href => "#"} San Diego
                            %li
                              %a{:href => "#"} Chula Vista
                            %li
                              %a{:href => "#"} Escondido
          %li.dropdown
            %a.dropdown-toggle{:href => "/pages/contact"}
              Contact Us
              = fa_icon "angle-down"

app/views/layouts/_vendor_and_javascript_files.html.haml
/ Libs
%script{:src => "/assets/vendor/jquery.js"}
%script{:src => "/assets/javascripts/plugins.js"}
%script{:src => "/assets/vendor/javascripts/jquery.easing.js"}
%script{:src => "/assets/vendor/javascripts/jquery.appear.js"}
%script{:src => "/assets/vendor/javascripts/jquery.cookie.js"}
%script{:src => "/assets/vendor/javascripts/bootstrap.js"}
%script{:src => "/assets/vendor/twitterjs/twitter.js"}
%script{:src => "/assets/vendor/rs-plugin/js/jquery.themepunch.plugins.min.js"}
%script{:src => "/assets/vendor/rs-plugin/js/jquery.themepunch.revolution.js"}
%script{:src => "/assets/vendor/owl-carousel/owl.carousel.js"}
%script{:src => "/assets/vendor/circle-flip-slideshow/js/jquery.flipshow.js"}
%script{:src => "/assets/vendor/magnific-popup/magnific-popup.js"}
%script{:src => "/assets/vendor/jquery.validate.js"}
/ Current Page Scripts
%script{:src => "/assets/javascripts/views/view.home.js"}
/ Theme Initializer
%script{:src => "/assets/javascripts/theme.js"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
	<title>MMA Gyms In California</title>
	<meta name="keywords" content="" />
	<meta name="description" content="">
	<meta name="author" content="cristian cisneros">

	<!-- Mobile Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Web Fonts  -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

	
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="body">
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		</div>
		<%#= render 'layouts/vendor_and_javascript_files' %>
	</body>
</html>

app/views/mma_gyms/_form.html.haml
= form_for @mma_gym do |f|
  - if @mma_gym.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mma_gym.errors.count, "error")} prohibited this mma_gym from being saved:"
      %ul
        - @mma_gym.errors.full_messages.each do |msg|
          %li= msg

  .row
  .form-group
  .col-md-6
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .row
  .form-group
  .col-md-6
    = f.label :address
    = f.text_field :address, class: 'form-control'
  .row
  .form-group
  .col-md-6
    = f.label :city
    = f.select :city, City.order("name ASC").map{|c| [c.name, c.name]}, class: 'form-control'
  .row
  .form-group
  .col-md-3
    = f.label :zip
    = f.text_field :zip, class: 'form-control'
  .row
  .form-group
  .col-md-3
    = f.label :state
    = f.select :state, options_for_select(%w[CA]), class: 'form-control'
  .row
  .form-group
  .col-md-3
    = f.label :phone
    = f.text_field :phone, class: 'form-control'    
  .row
  .form-group
  .col-md-3
    = f.label :website
    = f.text_field :website, class: 'form-control'
  .row
  .form-group
  .col-md-3
    = f.label :email
    = f.text_field :email, class: 'form-control'                
  .row
  .form-group
  .col-md-6
    = f.submit 'Save', class: 'btn btn-primary btn-lg'

app/views/mma_gyms/edit.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active Editing MMA Gym
      .row
        .col-md-12
          %h2 Editing MMA Gym

.container
  .row
    .col-md-12
    .row

%h1 Editing MMA Gym

= render 'form'

= link_to 'Show', @mma_gym, class: 'btn btn-default'
\|
= link_to 'Back', mma_gyms_path, class: 'btn btn-default'

app/views/mma_gyms/index.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active MMA Gyms In California
      .row
        .col-md-12
          %h2 MMA Gyms In California

.container
  .row
    .col-md-12

%h1 MMA Gyms In California

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th Name
      %th Address
      %th City
      %th Zip
      %th State
      %th Phone
      %th Website
      %th Email

  %tbody
    - @mma_gyms.each do |mma_gym|
      %tr
        %td= mma_gym.name
        %td= mma_gym.address
        %td= mma_gym.city
        %td= mma_gym.zip
        %td= mma_gym.state
        %td= mma_gym.phone
        %td= mma_gym.website
        %td= mma_gym.email
        %td= link_to 'Show', mma_gym, class: 'btn btn-info'
        %td= link_to 'Edit', edit_mma_gym_path(mma_gym), class: 'btn btn-default'
        %td= link_to 'Destroy', mma_gym, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

%br

= link_to 'New MMA Gym', new_mma_gym_path, class: 'btn btn-primary btn-lg'

app/views/mma_gyms/new.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active New MMA Gym
      .row
        .col-md-12
          %h2 New MMA Gym

.container
  .row
    .col-md-6
    .row

= render 'form'

.row
.form-group
.col-md-6
= link_to 'Back', mma_gyms_path, class: 'btn btn-default'

app/views/mma_gyms/show.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li
              %a{:href => "/mma_gyms/"} MMA Gyms
            %li.active = @mma_gym.name
      .row
        .col-md-12
          %h2 = @mma_gym.name

.container
  .row
    .col-md-6
    .row

%p#notice= notice

%h1
  %b Name:
  = @mma_gym.name
%h2
  %b Address:
  = @mma_gym.address
%h2
  %b City:
  = @mma_gym.city
%h2
  %b Zip:
  = @mma_gym.zip
%h2
  %b State:
  = @mma_gym.state
%h2
  %b Phone:
  = @mma_gym.phone
%h2
  %b Website:
  = @mma_gym.website
%h2
  %b Email:
  = @mma_gym.email   

.row
.form-group
.col-md-6
= link_to 'Edit', edit_mma_gym_path(@mma_gym), class: 'btn btn-default'
\|
= link_to 'Back', mma_gyms_path, class: 'btn btn-default'

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
.main{:role => "main"}
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Home
            %li.active Contact Us
      .row
        .col-md-12
          %h2 Contact Us


  .container
    .row
      .col-md-6
        #contactSuccess.alert.alert-success.hidden
          %strong Success!
          Your message has been sent to us.
        #contactError.alert.alert-danger.hidden
          %strong Error!
          There was an error sending your message.
        %h2.short
          %strong Contact
          Us
        %form#contactForm{:action => "php/contact-form.php", :type => "post"}
          .row
            .form-group
              .col-md-6
                %label Your name *
                %input#name.form-control{"data-msg-required" => "Please enter your name.", :maxlength => "100", :name => "name", :type => "text", :value => ""}
              .col-md-6
                %label Your email address *
                %input#email.form-control{"data-msg-email" => "Please enter a valid email address.", "data-msg-required" => "Please enter your email address.", :maxlength => "100", :name => "email", :type => "email", :value => ""}
          .row
            .form-group
              .col-md-12
                %label Subject
                %input#subject.form-control{"data-msg-required" => "Please enter the subject.", :maxlength => "100", :name => "subject", :type => "text", :value => ""}
          .row
            .form-group
              .col-md-12
                %label Message *
                %textarea#message.form-control{"data-msg-required" => "Please enter your message.", :maxlength => "5000", :name => "message", :rows => "10"}
          .row
            .col-md-12
              %input.btn.btn-primary.btn-lg{"data-loading-text" => "Loading...", :type => "submit", :value => "Send Message"}
      .col-md-6
        %h4.push-top
          Get in
          %strong touch
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget leo at velit imperdiet varius. In eu ipsum vitae velit congue iaculis vitae at risus.
        %hr/
        %h4
          The
          %strong Office
        %ul.list-unstyled
          %li
            = fa_icon "map-marker fw"
            %strong Address:
            1234 Street Name, City Name, United States
          %li
            = fa_icon "phone fw"
            %strong Phone:
            (123) 456-7890
          %li
            = fa_icon "envelope fw"
            %strong Email:
            %a{:href => "mailto:mail@example.com"} mail@example.com
        %hr/
        %h4
          Business
          %strong Hours
        %ul.list-unstyled
          %li
            = fa_icon "clock-o fw"
            Monday - Friday 9am to 5pm
          %li
            = fa_icon "clock-o fw"
            Saturday - 9am to 2pm
          %li
            = fa_icon "clock-o fw"
            Sunday - Closed
%section.call-to-action.featured.footer
  .container
    .row
      .center
        %h3
          Porto is
          %strong everything
          you need to create an
          %strong awesome
          website!
          %a.btn.btn-lg.btn-primary{"data-appear-animation" => "bounceIn", :href => "#", :target => "_blank"} Buy Now!
          %span.arrow.hlb{"data-appear-animation" => "rotateInUpLeft", :style => "top: -22px;"}

app/views/pages/mma_gyms.html.haml
%h1 Pages#mma_gyms
%p Find me in app/views/pages/mma_gyms.html.haml